// Generated by scripts/firmware-keygen.sh — do not edit by hand.
//
// The public half of the DeskNote firmware signing key. An over-the-air
// update is only installed if its ECDSA P-256 / SHA-256 signature verifies
// against this key. It is public on purpose; the private half never leaves
// the release machine.
#pragma once

static const char kFirmwareSigningPublicKey[] =
    "-----BEGIN PUBLIC KEY-----\n"
    "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE6NUxR1cHzSdt4x/SHTGgs9vGTSgu\n"
    "/zymqv3usOWqvRQDOL5bTx4hz4+hu1tERZ2GKMRCCL1uV2wu6tet1IOl5g==\n"
    "-----END PUBLIC KEY-----\n"
    ;
