// AUTO-GENERATED by scripts/gen_emoji_assets.py — do not edit.
// Mirrors kEmoji in firmware/desknote_hello/desknote_hello.ino so the
// composer only exposes emoji the desk can actually render.

export type SupportedEmoji = {
  char: string;
  cp: string;
  /** Short label shown in the picker; falls back to the codepoint. */
  name?: string;
  /** True when the glyph lives in the MDI Private Use Area and
   *  needs the MDI webfont to render. */
  mdi?: boolean;
};

export const SUPPORTED_EMOJI: SupportedEmoji[] = [
  { char: "\udb83\udc72", cp: 'U+F0C72', name: "kiss", mdi: true },
  { char: "\udb83\udc6d", cp: 'U+F0C6D', name: "cry", mdi: true },
  { char: "\udb80\uddf7", cp: 'U+F01F7', name: "poop", mdi: true },
  { char: "\udb83\udc78", cp: 'U+F0C78', name: "wink", mdi: true },
  { char: "\udb80\uddf9", cp: 'U+F01F9', name: "tongue", mdi: true },
  { char: "\udb83\udc74", cp: 'U+F0C74', name: "neutral", mdi: true },
  { char: "\udb80\uded2", cp: 'U+F02D2', name: "heart", mdi: true },
  { char: "\udb82\udfe3", cp: 'U+F0BE3', name: "you", mdi: true },
  { char: "\udb84\udcf1", cp: 'U+F10F1', name: "hug", mdi: true },
  { char: "\udb84\ude11", cp: 'U+F1211', name: "battery", mdi: true },
  { char: "\udb80\ude4a", cp: 'U+F024A', name: "flower", mdi: true },
  { char: "\udb87\udc73", cp: 'U+F1C73', name: "tree", mdi: true },
  { char: "\udb81\udd92", cp: 'U+F0592', name: "rain", mdi: true },
  { char: "\udb81\udda8", cp: 'U+F05A8', name: "sun", mdi: true },
  { char: "\udb81\udd9a", cp: 'U+F059A', name: "dusk", mdi: true },
  { char: "\udb83\udd08", cp: 'U+F0D08', name: "poppy", mdi: true },
  { char: "\udb83\udfa1", cp: 'U+F0FA1', name: "bee", mdi: true },
  { char: "\udb82\ude43", cp: 'U+F0A43', name: "dog", mdi: true },
  { char: "\udb80\udd1b", cp: 'U+F011B', name: "cat", mdi: true },
  { char: "\udb81\udfc6", cp: 'U+F07C6', name: "elephant", mdi: true },
  { char: "\udb80\uddc1", cp: 'U+F01C1', name: "usd", mdi: true },
  { char: "\udb80\udfd8", cp: 'U+F03D8', name: "palette", mdi: true },
  { char: "\udb81\udf85", cp: 'U+F0785', name: "sticker", mdi: true },
  { char: "\udb80\udd98", cp: 'U+F0198', name: "cookie", mdi: true },
  { char: "\udb82\udfad", cp: 'U+F0BAD', name: "1-up", mdi: true },
  { char: "\udb82\udfc9", cp: 'U+F0BC9', name: "alien", mdi: true },
  { char: "\udb86\udc18", cp: 'U+F1818', name: "bath", mdi: true },
  { char: "\udb80\udf87", cp: 'U+F0387', name: "music", mdi: true },
  { char: "\udb82\udd73", cp: 'U+F0973', name: "om", mdi: true },
  { char: "\udb80\uded1", cp: 'U+F02D1', name: "heart-line", mdi: true },
  { char: "\udb82\ude1c", cp: 'U+F0A1C', name: "vintage", mdi: true },
];
