#!/bin/bash
# Make the key pair that signs DeskNote firmware updates. Run once, ever.
#
#   ./scripts/firmware-keygen.sh
#
# A desk only installs an over-the-air update whose ECDSA P-256 signature
# checks out against the public key compiled into the firmware it is already
# running. So:
#
#   - The PRIVATE key stays on this Mac, at ~/.desknote/firmware-signing-key.pem,
#     outside the repo. Back it up (a password manager is fine). Lose it and
#     every desk in the field can only be updated over USB again.
#   - The PUBLIC key is written into the repo twice: as a PEM for
#     release-firmware.sh to self-check with, and as a C header the sketch
#     includes. Neither is secret.
#
# Refuses to replace an existing private key: doing so would strand every desk
# already trusting the old one.
set -euo pipefail
cd "$(dirname "$0")/.."

KEY_DIR="$HOME/.desknote"
PRIVATE="$KEY_DIR/firmware-signing-key.pem"
PUBLIC_PEM="firmware/firmware-signing.pub.pem"
HEADER="firmware/desknote_main/firmware_signing_key.h"

if [ -e "$PRIVATE" ]; then
  echo "A signing key already exists at $PRIVATE — not replacing it."
  echo "Regenerating the public files from it instead."
else
  mkdir -p "$KEY_DIR"
  chmod 700 "$KEY_DIR"
  (umask 077 && openssl ecparam -name prime256v1 -genkey -noout -out "$PRIVATE")
  chmod 600 "$PRIVATE"
  echo "New private key: $PRIVATE  — back this file up now."
fi

openssl ec -in "$PRIVATE" -pubout -out "$PUBLIC_PEM" 2>/dev/null

{
  echo "// Generated by scripts/firmware-keygen.sh — do not edit by hand."
  echo "//"
  echo "// The public half of the DeskNote firmware signing key. An over-the-air"
  echo "// update is only installed if its ECDSA P-256 / SHA-256 signature verifies"
  echo "// against this key. It is public on purpose; the private half never leaves"
  echo "// the release machine."
  echo "#pragma once"
  echo
  echo "static const char kFirmwareSigningPublicKey[] ="
  while IFS= read -r line; do printf '    "%s\\n"\n' "$line"; done < "$PUBLIC_PEM"
  echo "    ;"
} > "$HEADER"

echo "Public key: $PUBLIC_PEM"
echo "Header:     $HEADER"
