#!/usr/bin/env python3
"""
Parse firmware/desknote_hello/desknote_hello.ino for kEmoji UTF-8 rows, download
Twemoji PNGs (CC-BY 4.0), resize to RGB565, emit emoji_assets.gen.h

Run from repo root:
  python3 scripts/gen_emoji_assets.py

Requires: Pillow, network (first run). Re-run after changing the kEmoji table.
"""
from __future__ import annotations

import re
import ssl
import sys
import urllib.request
from pathlib import Path

# Asset fetch uses Twemoji CDN; allow unverified TLS so `python3 scripts/...`
# works on machines without full CA bundles (CI / dev). Regenerate before release
# if you require strict verification.
def _urlopen(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": "DeskNote-asset-gen"})
    ctx = ssl._create_unverified_context()
    with urllib.request.urlopen(req, timeout=30, context=ctx) as resp:
        return resp.read()

try:
    from PIL import Image
except ImportError:
    print("Install Pillow: pip install Pillow", file=sys.stderr)
    sys.exit(1)

REPO = Path(__file__).resolve().parents[1]
INO = REPO / "firmware/desknote_hello/desknote_hello.ino"
OUT = REPO / "firmware/desknote_hello/emoji_assets.gen.h"

SPRITE = 20  # width & height in px (RGB565)
TWEMOJI_BASE = (
    "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/{}.png"
)


def twemoji_filename(cp: int) -> str:
    return f"{cp:x}.png"


def parse_kemoji(path: Path) -> list[tuple[int, bytes]]:
    """Return list of (utf8_len, utf8_bytes) in file order."""
    text = path.read_text(encoding="utf-8")
    pat = re.compile(
        r"\{(\d+)\s*,\s*\{([^}]*)\}\s*,\s*\"[^\"]*\"\s*\}",
        re.MULTILINE,
    )
    rows: list[tuple[int, bytes]] = []
    for m in pat.finditer(text):
        ln = int(m.group(1))
        inner = m.group(2)
        nums = [int(x.strip(), 16) for x in inner.split(",") if "0x" in x]
        if len(nums) < ln:
            continue
        b = bytes(nums[:ln])
        rows.append((ln, b))
    return rows


def utf8_to_cp(b: bytes) -> int:
    return ord(b.decode("utf-8"))


def rgb565(r: int, g: int, b: int) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def png_to_rgb565(png_bytes: bytes, size: int) -> list[int]:
    im = Image.open(__import__("io").BytesIO(png_bytes)).convert("RGBA")
    im = im.resize((size, size), Image.Resampling.LANCZOS)
    out: list[int] = []
    for y in range(size):
        for x in range(size):
            r, g, b, a = im.getpixel((x, y))
            if a < 128:
                r, g, b = 0, 0, 0
            out.append(rgb565(r, g, b))
    return out


def fetch_png(cp: int) -> bytes:
    url = TWEMOJI_BASE.format(twemoji_filename(cp).replace(".png", ""))
    return _urlopen(url)


def main() -> None:
    rows = parse_kemoji(INO)
    if not rows:
        print("No kEmoji rows parsed from", INO, file=sys.stderr)
        sys.exit(1)

    cps_in_order: list[int] = []
    for ln, b in rows:
        cps_in_order.append(utf8_to_cp(b))

    unique_cps = []
    seen: set[int] = set()
    for cp in cps_in_order:
        if cp not in seen:
            seen.add(cp)
            unique_cps.append(cp)

    cp_to_uid: dict[int, int] = {cp: i for i, cp in enumerate(unique_cps)}

    print(
        f"Parsed {len(rows)} emoji rows, {len(unique_cps)} unique codepoints, "
        f"{SPRITE}x{SPRITE} RGB565 sprites",
        file=sys.stderr,
    )

    sprite_pixels: list[list[int]] = []
    def synth_em_dash() -> list[int]:
        pix = [rgb565(0, 0, 0)] * (SPRITE * SPRITE)
        mid = SPRITE // 2
        for x in range(3, SPRITE - 3):
            pix[mid * SPRITE + x] = rgb565(200, 200, 200)
        return pix

    for i, cp in enumerate(unique_cps):
        try:
            if cp == 0x2014:
                pix = synth_em_dash()
            else:
                png = fetch_png(cp)
                pix = png_to_rgb565(png, SPRITE)
        except Exception as e:
            print(f"WARN: cp U+{cp:X} fetch failed ({e}), using replacement", file=sys.stderr)
            try:
                png = fetch_png(0x2753)  # question mark
                pix = png_to_rgb565(png, SPRITE)
            except Exception:
                pix = [rgb565(80, 80, 80)] * (SPRITE * SPRITE)
        sprite_pixels.append(pix)
        print(f"  [{i+1}/{len(unique_cps)}] U+{cp:X}", file=sys.stderr)

    row_sprite_idx = [cp_to_uid[cp] for cp in cps_in_order]

    lines: list[str] = [
        "/* AUTO-GENERATED by scripts/gen_emoji_assets.py — do not edit. */",
        "/* Twemoji artwork © Twitter, Inc. / CC-BY 4.0 */",
        "#ifndef DESKNOTE_EMOJI_ASSETS_GEN_H",
        "#define DESKNOTE_EMOJI_ASSETS_GEN_H",
        "#include <stdint.h>",
        "",
        f"#define EMOJI_SPRITE_PX {SPRITE}",
        f"#define EMOJI_UNIQUE_SPRITES {len(unique_cps)}",
        f"#define EMOJI_TABLE_ROWS {len(rows)}",
        "",
        f"static const uint16_t kEmojiSpriteData[EMOJI_UNIQUE_SPRITES][EMOJI_SPRITE_PX * EMOJI_SPRITE_PX] = {{",
    ]

    for uid, pix in enumerate(sprite_pixels):
        lines.append("  {")
        for row_start in range(0, len(pix), SPRITE):
            chunk = pix[row_start : row_start + SPRITE]
            hexes = ", ".join(f"0x{v:04X}" for v in chunk)
            lines.append(f"    {hexes},")
        lines.append("  },")

    lines.append("};")
    lines.append("")
    lines.append("static const uint8_t kEmojiRowSpriteIdx[EMOJI_TABLE_ROWS] = {")
    buf: list[str] = []
    col = 0
    for v in row_sprite_idx:
        s = str(v)
        if buf and col + len(s) + 2 > 100:
            lines.append("  " + ", ".join(buf) + ",")
            buf = []
            col = 0
        buf.append(s)
        col += len(s) + 2
    if buf:
        lines.append("  " + ", ".join(buf))
    lines.append("};")
    lines.append("")
    lines.append("#endif")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("Wrote", OUT, file=sys.stderr)


if __name__ == "__main__":
    main()
